packages:
  - .
engineStrict: true
allowBuilds:
  unrs-resolver: true
  '@parcel/watcher': true
  esbuild: true
  lightningcss-cli: true
catalog:
  react: 19.2.8
  react-dom: 19.2.8
  typescript: 6.0.3
